version: 2.1

workflows:
  main-workflow:
    jobs:
      - main-job

jobs:
  main-job:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn

      - run: yarn nps lint
