name: lint

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: kirkstrobeck/nextjs-starter/.github/workflows/setup.yml@main

      - run: yarn --prefer-offline

      - run: yarn nps lint
