name: main

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    # container: node:16

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn --prefer-offline

      - run: yarn nps lint
